dist: focal
sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t unshesh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true unshesh/react-test npm test

after_success:
  - docker build -t $DOCKER_ID/multi-client ./client
  - docker build -t $DOCKER_ID/multi-nginx ./nginx
  - docker build -t $DOCKER_ID/multi-server ./server
  - docker build -t $DOCKER_ID/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push $DOCKER_ID/multi-client
  - docker push $DOCKER_ID/multi-nginx
  - docker push $DOCKER_ID/multi-server
  - docker push $DOCKER_ID/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-552278708710"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
